# Study variables -----------------------------------------------------
study_accession: PRJNA380944
sample_regex: '\.D\d?$'
# Processing parameters -----------------------------------------------
trim-length: 253
min-reads: 1
alpha-diversity-metric: observed_otus
# Implementation parameters -------------------------------------------
jobs-to-start: 2
# Filenames -----------------------------------------------------------
filereport: filereport.txt
manifest: manifest.csv
demux: demux.qza
filter: filter.qza
filter-stats: filter-stats.qza
table: table.qza
rep-seqs: rep-seqs.qza
denoise-stats: denoising-stats.qza
table-tsv: table.tsv
rarefaction-depth: depth.txt
rarefied-table: rarefied-table.qza
alpha-diversity: alpha-diversity.qza
